INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '9:00 AM – 11:00 AM', 'Plenary', 'A corporation as big as a small country: Towards an Agile enterprise', 'Jeff Smith');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '9:00 AM – 11:00 AM', 'Plenary', 'Changing mindsets to build an Agile country', 'Peter Halacsy');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '9:00 AM – 11:00 AM', 'Plenary', 'Robot Ethics and the Future of Human-Robot Interaction', 'Kate Darling');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '11:30 AM', '220', 'Towards an Agile Country', 'Daniel Petre');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '11:30 AM', '213', 'Taking a hypothesis-driven approach', 'Nicola Boyle and Robert Harrison');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '11:30 AM', '211', 'The neuroscience of human agility in organisations', 'Melissa Casey');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '11:30 AM', '210', 'Rescuing legacy software from impending doom', 'Martin Cronjé and Jacques De Vos');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '11:30 AM', '217', 'Scaled Agile: A Federal Government Implementation', 'Robert McKinnon and Corey Lewis');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '12:15 PM', '220', 'Scaling as the tide turns', 'Cameron Gough');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '12:15 PM', '213', 'Enterprise agility through OCM and Agile', 'Jennifer Frahm');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '12:15 PM', '211', 'Smashing the monolith', 'Leonard Garvey and Louis Simoneau');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '12:15 PM', '210', '5 sketches on whiteboards', 'Glyn Thomas');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '12:15 PM', '217', 'Deep Dive', 'Jeff Smith');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '2:00 PM', '220', 'Simply Buurtzorg: adaptive agility for individual and local needs', 'Nicole Koster');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '2:00 PM', '213', 'Coaching product owners effectively', 'Karen Greaves and Samantha Laing');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '2:00 PM', '211', 'Continuous improvement at scale', 'Ryan McKergow');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '2:00 PM', '210', 'Activate Agile', '');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '2:00 PM', '217', 'A new approach for enterprises that measures Business Agility Health', 'Brad Bennett and Rob Gaunt');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '2:45 PM', '220', 'Agile leadership: an approach for leaders in large-scale and start-up companies', 'Lisa Frazier');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '2:45 PM', '213', 'Career growth with impact', 'Tom Adams and Georg Friedrich');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '2:45 PM', '211', 'Using a design sprint to accelerate innovation', 'Rob Alford and Rob Scherer');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '2:45 PM', '210', 'Activate Agile', '');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '2:45 PM', '217', 'Deep Dive', 'Nicole Koster');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '4:00 PM', '220', 'Kata – Habits for Lean learning', 'Håkan Forss');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '4:00 PM', '213', 'Making each other look good', 'The Spark Team');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '4:00 PM', '211', 'Event Sourcery', 'James Ross and Sebastian Von Conrad');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '4:00 PM', '217', 'Mission impossible: banking on a SAFe Quick Start', 'Em Campbell-Pretty');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '4:00 PM', 'Plenary', 'Activate Agile - Q+A with Peter Halacsy', '');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '4:45 PM', '220', 'Moving towards an Agile workplace', 'Robyn Dunn');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '4:45 PM', '213', '7 things that Agile executives and leaders do differently', 'Dipesh Pala');
INSERT INTO talks (day, time, room, name, speakers) values ('Monday 20 June 2016', '4:45 PM', '211', 'Creating great teams – how self-selection lets people excel', 'Sandy Mamoli and David Mole');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '7:30 AM', 'Open Space', 'Lean Coffee Meetup', '');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '9:00 AM', 'Plenary', 'You''re not doing usability testing? Are you…nuts?', 'Steve Krug');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '10:00 AM', 'Plenary', 'Awesome Superproblems', 'Luke Hohmann');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '11:30 AM', '220', 'Creating a kaizen culture proves transformative for Food Bank of New York City', 'Margarette Purvis');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '11:30 AM', '213', 'You want me to do what? The journey from business person to product owner', 'Chris Bignoux and Pete Cohen');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '11:30 AM', '211', 'Using Collaborative Communication for teamwork and transparency', 'Shari Elle and Nicholas Ho');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '11:30 AM', '210', 'Apps and APIs: best friends forever', 'Stewart Gleadow');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '11:30 AM', '217', 'Deep Dive', 'Håkan Forss');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '12:15 PM', '220', 'Agile at scale in the UK Government', 'Duncan Crawford and Alun Coppack');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '12:15 PM', '213', 'The heart of Agile is in your local primary school', 'Richard Weissel');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '12:15 PM', '211', 'Using visual management to introduce Lean thinking', 'Ben Hogan');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '12:15 PM', '210', 'Lightning Talks', '');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '12:15 PM', '217', 'Deep Dive', 'Margarette Purvis');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '2:00 PM', '220', 'Towards a more inclusive workplace', 'Jane Burns and Aaron Hodder');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '2:00 PM', '213', 'Smoothing the Continuous Delivery path: a tale of two teams', 'Lyndsay Prewer');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '2:00 PM', '211', 'Towards organisational alignment and agility', 'Ben Ross');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '2:00 PM', '210', 'Design tips for the non-designer', 'Emma Carter');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '2:00 PM', '217', 'Deep Dive', 'Luke Hohmann');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '2:45 PM', '220', 'Rethinking performance and improvement with the Vanguard Method', 'Tim Banner and David Joyce');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '2:45 PM', '213', 'Data-driven culture', 'Jo Cranford');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '2:45 PM', '211', 'Get faster everywhere – simplify then add lightness', 'Kelsey van Haaster');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '2:45 PM', '210', 'Lightning Talks', '');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '2:45 PM', '217', 'Deep Dive', 'Steve Krug');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '4:00 PM', '220', 'Better project forecasts without estimates – The Monte Carlo', 'Adrian Fittolani');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '4:00 PM', '213', 'Coaching Nightmares: insights we can learn from Gordon Ramsay', 'Renee Troughton and Craig Smith');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '4:00 PM', '211', 'How a blues band taught me to build Agile teams that rock!', 'Brett Wakeman and Nigel Dalton');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '4:45 PM', '220', 'Leveraging mindsets for effective leadership', 'Peter Heslin');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '4:45 PM', '213', 'Failing @ Scaling: don''t panic, and carry a towel!', 'Em Campbell-Pretty and Mark Richards');
INSERT INTO talks (day, time, room, name, speakers) values ('Tuesday 21 June 2016', '4:45 PM', '211', 'Coming to terms with ''near enough''', 'Megan Dell');
